name: frontend_merallin
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  # Disesuaikan untuk Flutter 3.10.0
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- VERSI DIPERBARUI ---
  flutter_speed_dial: ^7.0.0
  device_info_plus: ^10.1.0
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.0
  dio: ^5.5.0+1
  flutter_local_notifications: ^17.2.1+1
  open_filex: ^4.4.0
  url_launcher: ^6.3.0
  http_parser: ^4.0.2 
  mime: ^1.0.5
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  intl: ^0.20.2      
  geolocator: ^12.0.0     
  image_picker: ^1.1.2     
  permission_handler: ^11.3.1
  file_picker: ^8.0.6
  image: ^4.2.0
  geocoding: ^3.0.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  flutter_pdfview: ^1.3.2
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  timezone: ^0.9.4
  camera: ^0.10.6
  camera_windows: ^0.2.1+1
  # downloads_path_provider_28: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  msix: ^3.16.12

msix_config:
  display_name: frontend_merallin
  publisher_display_name: Farhan Muzakki
  identity_name: com.farhan.frontendmerallin
  msix_version: 1.0.0.0
  logo_path: windows\runner\resources\app_icon.ico
  capabilities: "internetClient,location"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/MERALLIN_LOGO_WAITING.svg"
  android_gravity: "center"
  ios_content_mode: "center"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo_meralin_besar.jpeg
    - assets/MERALLIN_LOGO_WAITING.svg


  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial/ARIAL.TTF
        
        - asset: assets/fonts/arial/ARIALI.TTF
          style: italic
        
        - asset: assets/fonts/arial/ARIALBD.TTF
          weight: 700 # Bold
          
        - asset: assets/fonts/arial/ARIALBI.TTF
          weight: 700
          style: italic
          
        - asset: assets/fonts/arial/ARIALBLACKITALIC.TTF 
          weight: 900                              
          style: italic