name: frontend_merallin
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  # Disesuaikan untuk Flutter 3.10.0
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 6.1.14

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  http: ^0.13.5
  
  # --- PASTIKAN DUA BARIS INI ADA ---
  intl: ^0.18.0           
  geolocator: ^9.0.2      
  image_picker: ^0.8.9      
  permission_handler: ^10.4.5 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo_meralin_besar.jpeg
